name: Check Checkbox Before Merge

on:
  pull_request:
    types:
      - synchronize
      - labeled
      - unlabeled

jobs:
  check_checkbox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Checkbox
        id: checkbox
        run: |
          PR_BODY=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                            -H "Accept: application/vnd.github.v3+json" \
                            "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r '.body')

          # Check if the checkbox is checked
          if [[ "$PR_BODY" == *"[x]"* ]]; then
            echo "Checkbox is checked. Proceeding with merge."
          else
            echo "Checkbox is not checked. Cannot merge."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
