name: Update Comment on Label Changes

on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  update_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read Labels from labels.yml
        id: read_labels
        run: echo "::set-output name=labels::$(cat labels.yml)"

      - name: Update Comment
        uses: actions/github-script@v4
        with:
          script: |
            const labels = ${{ steps.read_labels.outputs.labels }};
            const labelNames = labels.map(label => label.name);
            const body = `Please review the code carefully before merging and check the following box if the correct type of version is going to be merged\n\n- [ ] This PR means a new version of the package ("${labelNames.join(', ')}")`;
            const comments = await github.issues.listComments({ issue_number: context.issue.number, owner: context.repo.owner, repo: context.repo.repo });
            const commentToUpdate = comments.data.find(comment => comment.body.includes('This PR means a new version of the package ('));
            if (commentToUpdate) {
              github.issues.updateComment({ comment_id: commentToUpdate.id, owner: context.repo.owner, repo: context.repo.repo, body });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
